language: node_js
node_js:
  - '10'
  - '8'

cache: yarn

deploy:
  provider: script
  skip_cleanup: true
  script:
    - yarn travis-deploy-once "yarn semantic-release"

branches:
  only:
    - master
